package com.example.practice.common.response;

public enum RestApiMessage {
    USER_NOT_FOUND,
    INVALID_REQUEST,
    NAME_ALREADY_EXIST,
    CATEGORY_NOT_FOUND,
    DATA_NOT_CHANGE,
    DATA_SAME_OLD_DATA,
    CANNOT_DELETED_WHILE_CHILDREN_EXISTED,
    PARENT_ID_CANNOT_EMPTY,
    CATEGORY_NOT_FOUND_BY_PARENT_ID
}
